In [2]:
import numpy as np
# 1) 数组操作
print(np.zeros([2,2]),'\n')
print(np.ones([2,2]),'\n')
print(np.eye(2),'\n')
print(np.empty([3,3]),'\n')
print(np.full([3,3],6),'\n')
print(np.linspace(0,100,10))

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]] 

[[1. 0.]
 [0. 1.]] 

[[6.91885742e-310 6.91885742e-310 8.68157627e-169]
 [3.55701425e-106 2.33321764e-101 7.09714276e-164]
 [7.96563159e-063 1.16726736e-120 1.04156469e-144]] 

[[6 6 6]
 [6 6 6]
 [6 6 6]] 

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [3]:
a = np.array([1,2,3])
print(a.shape)
print(a.size)
a[0] = 5
print(a[0],a[1],a[2])
b = np.array([[1,2,3],[4,5,6]])
print(b[0,0],b[0,1],b[1,0])

(3,)
3
5 2 3
1 2 4


In [4]:
# 2)	数组内元素指定不同数据类型
arr1 = np.array([1,2,3],dtype=np.float64)
arr2 = np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [5]:
# 3)  使用索引和切片的方式获取和修改数据
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[1] = 999
print(arr)
arr_slice[:]=14
print(arr)
names = np.array(['Bob','Will','Bob','Joe'])
data = np.array([[-3,2,0,-1],[1,2,3,-4],[2.5,1.7,-0.2,1],[-8,-4,9,10]])
print(data[names=='Bob'])
print(data[names=='Bob',2:])

[  0   1   2   3   4   5 999   7   8   9]
[ 0  1  2  3  4 14 14 14  8  9]
[[-3.   2.   0.  -1. ]
 [ 2.5  1.7 -0.2  1. ]]
[[ 0.  -1. ]
 [-0.2  1. ]]


In [6]:
# 4)	NumPy中内置的一些常用的统计方法
arr3 = np.arange(20).reshape((4,5))
print("arr3:",arr3)
print('arr的平均值',arr3.mean())
print('arr的和',arr3.sum())
print('arr的每行的平均值',arr3.mean(1))
print('arr的每列的和',arr3.sum(0))

arr3: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
arr的平均值 9.5
arr的和 190
arr的每行的平均值 [ 2.  7. 12. 17.]
arr的每列的和 [30 34 38 42 46]
