In [26]:
import numpy as np
import pandas as pd

# 2)	创建Series和DataFrame
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s,'\n')
data1 = {'a':0.,'b':1.,'c':2.}
s1 = pd.Series(data1)
print(s1)

df = pd.DataFrame(np.random.randn(7,4),columns=list('ABCD'))
print('\n',df)

0    a
1    b
2    c
3    d
dtype: object 

a    0.0
b    1.0
c    2.0
dtype: float64

           A         B         C         D
0 -0.187160 -0.100597 -1.205335  0.654190
1  0.666495  1.014256 -2.112572  0.198527
2 -0.412037  0.215168  2.706994  0.692147
3  0.048851 -1.528333 -1.530478 -0.470729
4  0.568497  0.573357 -0.489107 -1.754290
5  0.141523  1.182714  0.164567 -0.727051
6 -0.786473 -1.042042  0.966375  2.194778


In [27]:
df1 = pd.DataFrame({'A':1.,
                    'B':pd.Timestamp(2190102),
                    'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D':np.array([3] * 4,dtype='int32'),
                    'E':pd.Categorical(['test','train','test','train']),
                    'F':'foo'})
print(df1)

     A                             B    C  D      E    F
0  1.0 1970-01-01 00:00:00.002190102  1.0  3   test  foo
1  1.0 1970-01-01 00:00:00.002190102  1.0  3  train  foo
2  1.0 1970-01-01 00:00:00.002190102  1.0  3   test  foo
3  1.0 1970-01-01 00:00:00.002190102  1.0  3  train  foo


In [28]:
# 3)	DataFrame数据的操作
# a. 查看顶部和底部的数据
data2 = np.arange(30).reshape(6,5)
df2 = pd.DataFrame(data2,index=['a','b','c','d','e','f'],columns=['A','B','C','D','E'])
print(df2)
print("--" * 10)
print(df2.head())
print("--" * 10)
print(df2.tail(3))

    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
--------------------
    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
--------------------
    A   B   C   D   E
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29


In [30]:
# b.显示索引，列和数据
print("index is :")
print(df2.index)
print("columns is :")
print(df2.columns)
print("values is :")
print(df2.values)

index is :
Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')
columns is :
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
values is :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [34]:
# c. 使用loc方法，根据列名对相关索引进行切片，得到想要访问的数据
print(df2.loc['a':'f':2,'A'])
# d. 查看数据的详细信息
print(df2.describe)

a     0
c    10
e    20
Name: A, dtype: int64
<bound method NDFrame.describe of     A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29>


In [35]:
# 4)	DataFrame数据的操作
# a.使用drop方法删除不需要的列或行
data3 = np.arange(30).reshape(6,5)
df3 = pd.DataFrame(data3,index=['a','b','c','d','e','f'],columns = ['A','B','C','D','E'])
a = df3.drop(['a'],axis=0)
b = df3.drop(['A'],axis=1)
print('-------原始数据df-----')
print(df3)
print('--------删除行--------')
print(a)
print('--------删除列--------')
print(b)

-------原始数据df-----
    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
--------删除行--------
    A   B   C   D   E
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
f  25  26  27  28  29
--------删除列--------
    B   C   D   E
a   1   2   3   4
b   6   7   8   9
c  11  12  13  14
d  16  17  18  19
e  21  22  23  24
f  26  27  28  29


In [41]:
# b. 使用append方法合并两个DataFrame
c = b.append(a)
print(b)
print('----合并后的数据-----')
print(c)

    B   C   D   E
a   1   2   3   4
b   6   7   8   9
c  11  12  13  14
d  16  17  18  19
e  21  22  23  24
f  26  27  28  29
----合并后的数据-----
    B   C   D   E     A
a   1   2   3   4   NaN
b   6   7   8   9   NaN
c  11  12  13  14   NaN
d  16  17  18  19   NaN
e  21  22  23  24   NaN
f  26  27  28  29   NaN
b   6   7   8   9   5.0
c  11  12  13  14  10.0
d  16  17  18  19  15.0
e  21  22  23  24  20.0
f  26  27  28  29  25.0


In [40]:
# c. 删除带有NaN的数据
df10 = pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','there'])
df10 = df10.reindex(['a','b','c','d','e','f','g','h'])
print(df10)
print("---"*10)
print(df10.dropna())


        one       two     there
a  1.225337 -0.634983 -1.841215
b       NaN       NaN       NaN
c -0.259550  0.581526  0.489232
d       NaN       NaN       NaN
e -0.127961  0.964353  1.708543
f  0.302743  0.946849 -0.531337
g       NaN       NaN       NaN
h -1.233125 -0.284156 -0.370522
------------------------------
        one       two     there
a  1.225337 -0.634983 -1.841215
c -0.259550  0.581526  0.489232
e -0.127961  0.964353  1.708543
f  0.302743  0.946849 -0.531337
h -1.233125 -0.284156 -0.370522
